# Generated by Django 4.0.3 on 2022-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccelerometerRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.CharField(blank=True, max_length=255)),
                ('y_axis', models.CharField(blank=True, max_length=255)),
                ('z_axis', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesObtained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.CharField(blank=True, max_length=255)),
                ('std', models.CharField(blank=True, max_length=255)),
                ('kurtosis', models.CharField(blank=True, max_length=255)),
                ('skewness', models.CharField(blank=True, max_length=255)),
                ('crest', models.CharField(blank=True, max_length=255)),
                ('clearance', models.CharField(blank=True, max_length=255)),
                ('shape', models.CharField(blank=True, max_length=255)),
                ('impulse', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
