# Generated by Django 4.0.3 on 2022-05-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorOneBearingTwoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.CharField(blank=True, max_length=255)),
                ('y_axis', models.CharField(blank=True, max_length=255)),
                ('z_axis', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorTwoBearingOneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.CharField(blank=True, max_length=255)),
                ('y_axis', models.CharField(blank=True, max_length=255)),
                ('z_axis', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorTwoBearingTwoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.CharField(blank=True, max_length=255)),
                ('y_axis', models.CharField(blank=True, max_length=255)),
                ('z_axis', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AccelerometerRawData',
            new_name='SensorOneBearingOneData',
        ),
        migrations.AddField(
            model_name='featuresobtained',
            name='name',
            field=models.CharField(blank=True, choices=[('S1B1', 'S1B1'), ('S1B2', 'S1B2'), ('S2B1', 'S2B1'), ('S2B2', 'S2B2')], max_length=255),
        ),
    ]
