# Generated by Django 4.0.3 on 2022-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensoronebearingtwodata_sensortwobearingonedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorOneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('y_axis', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('z_axis', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorTwoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('y_axis', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('z_axis', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorOneBearingOneData',
        ),
        migrations.DeleteModel(
            name='SensorOneBearingTwoData',
        ),
        migrations.DeleteModel(
            name='SensorTwoBearingOneData',
        ),
        migrations.DeleteModel(
            name='SensorTwoBearingTwoData',
        ),
        migrations.AddField(
            model_name='featuresobtained',
            name='axis',
            field=models.CharField(blank=True, choices=[('x', 'x'), ('y', 'y')], max_length=255),
        ),
    ]
