# Generated by Django 4.0.3 on 2022-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sensoronedata_sensortwodata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoronedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensortwodata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
