# Generated by Django 4.0.3 on 2022-05-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_featuresobtained_clearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresobtained',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuresobtained',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
